# Generated by xtables-save v1.8.2 on Tue Apr 12 09:13:46 2022
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:S1 - [0:0]
-A FORWARD -d 192.168.100.80/32 -j S1
-A S1 -p tcp -m multiport --dports 80,8080 -j ACCEPT
-A S1 -p tcp -m tcp --dport 22 -j ACCEPT
-A S1 -j REJECT --reject-with icmp-port-unreachable
COMMIT
# Completed on Tue Apr 12 09:13:46 2022
